name: Add Developer Profile
description: Submit your profile to be added to the Effect developer directory.
title: "Developer Profile: [Your Name]"
labels: ["developer-submission"]
body:
  - type: input
    id: name
    attributes:
      label: Full name
      placeholder: "Jane Doe"
    validations:
      required: true

  - type: input
    id: location
    attributes:
      label: Location (country + timezone preferred)
      placeholder: "United States (UTC-5)"
    validations:
      required: true

  - type: checkboxes
    id: type
    attributes:
      label: Availability
      options:
        - label: Freelance
        - label: Full-Time
        - label: Consulting
        - label: Contract

  - type: input
    id: github
    attributes:
      label: GitHub profile URL
      placeholder: "https://github.com/yourhandle"

  - type: input
    id: X
    attributes:
      label: X(Twitter) profile URL 
      placeholder: "https://linkedin.com/in/yourprofile"

  - type: input
    id: linkedin
    attributes:
      label: LinkedIn profile URL 
      placeholder: "https://linkedin.com/in/yourprofile"

  - type: input
    id: Discord
    attributes:
      label: Discord handle
      placeholder: "@discord handle"

  - type: input
    id: other
    attributes:
      label: Personal website, portfolio, or other projects
      placeholder: "https://yourwebsite.dev"

  - type: textarea
    id: bio
    attributes:
      label: Short bio
      placeholder: "Tell us about your background and experience with Effect..."
    validations:
      required: true
